#docker-compose.yml
version: '3.4'
services:

  sbgn-rest-renderer:
    build:
      context: ./
      dockerfile: docker/Dockerfile

    image: sbgn-rest-renderer
    container_name: sbgn-rest-renderer
    restart: always
        
    ports: 
      - "8082:80"
      
