#docker-compose.yml
version: '3.4'
services:

  sbgn-rest-renderer:
    build:
      context: ./
      dockerfile: docker/Dockerfile

    image: sbgn-rest-renderer
    container_name: sbgn-rest-renderer
    restart: always
        
    ports: 
      - "8082:80"
      - "9091:8081"
      
  # newt-converter-dev:
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile

  #   image: newt-converter
  #   container_name: newt-converter
  #   restart: always
        
  #   ports: 
  #     - "8081:80"
    # volumes:
    #   - .:/var/sbgn-rest-renderer